### ISSUE TITLE
Rewrite in Swift?

### ISSUE THREAD

**Issue by xiruizhao** [westfeld/networkinterfacedetector#1]
I'm learning swift and don't know objective-c. I'm trying a write a Dynamic DNS update program.

**Comment by westfeld** [comment]
Thanks for your comment. Actually this SystemConfiguration API [Documentation](https://developer.apple.com/documentation/systemconfiguration) is not an Objective-C framework, but a C library.

You can use C code in Swift. You should find a good starting point [in this documentation](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/using_imported_c_functions_in_swift).
